[package]
name = "smf"
version = "0.10.0"
edition = "2021"

[dependencies]
libc = "0.2"
libscf-sys = { path = "/ws/libscf-sys" }
#libscf-sys = { git = "https://github.com/illumos/libscf-sys.git" }
num-traits = "0.2"
thiserror = "1"
